version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server
  aspnetapp:
    build: .
    restart: always
    ports:
      - 1488:80
    environment:
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=User Id=postgres;Password=postgres;Host=db;Port=5432;Database=server
